### ISSUE TITLE
Setup problem nanos-1314

### ISSUE THREAD

**Issue by stan2100** [LedgerHQ/nanos-secure-sdk#18]
Hi,
I have set up the environment on Linux 18.04.1 LTS virtual machine. I downloaded nanos-ui version 1.3.1. When I run the command make load, I get the failure: 

*"ImportError: No module named PIL
Traceback (most recent call last):
File "/home/ubuntu/bolos-devenv/nanos-secure-sdk-nanos-1314/icon.py", line 20,”*

What could be the cause for this? 
And how can I mount my ledger nano s  in recovery mode to the VM. When I hold the right button, recovery shows only for approx. 5 seconds on my nano s, and furthermore, the ledger nano s doesn’t show up in USB Device in my VM, only while in recovery mode.
Thank you in advance for your help!!!

**Comment by danuker** [comment]
The `ImportError` you get is a Python library that is missing. PIL is used for converting the icons. To install it, you have to run `pip install Pillow`.

As for recovery mode, I don't know how to do that, sorry. Could it help that you don't need a VM anymore, and that you only need a Linux env? https://ledger.readthedocs.io/en/latest/userspace/getting_started.html

**Comment by xchapron-ledger** [comment]
Closing it as this one is old ad probably already fix. Please repoen if need.
