### ISSUE TITLE
Makefile.glyphs Not producing Glyph Header/Source

### ISSUE THREAD

**Issue by Moejoe90** [LedgerHQ/nanos-secure-sdk#2]
For some reason when i try to compile the Blue-Eth-App i had a problem with Glyph.h not being found. 
After Further research i realized that in the SDK there is a glyph generating code that should run and generate the needed files. 
However for some reason when i tried to generate the files automatically even changing and hard-coding `GLYPH_SRC_DIR` , `BOLOS_SDK` and other parameters still things didn't work out and i would always get a `Makefile glyph.h is up to date` letter in the terminal which is not the case for sure.

**Comment by Moejoe90** [comment]
I just realized that the `makefile` for that project is outdated i managed to find a workaround until an official update comes

**Comment by mandelmonkey** [comment]
@Moejoe90 I have the same issue on the blue-btc-app what was the work around you used?
