### ISSUE TITLE
Nano X support

### ISSUE THREAD

**Issue by daira** [LedgerHQ/nanos-secure-sdk#22]
Does this also support the Nano X? If not, when is it likely to be supported, or is there a separate SDK?

Cc: @str4d

**Comment by andrepatta** [comment]
I'm wondering the same. I need a Ledger for development purposes but not sure which one is best suited (Nano S or Nano X).

**Comment by daira** [comment]
I guess based on the wording of [this update](https://github.com/LedgerHQ/nanos-secure-sdk/commit/1f2706941b68d897622f75407a868b60eb2be8d7#diff-04c6e90faac2675aa89e2176d2eec7d8) that there is now supposed to be some Nano X support? This is still pretty unclear given that the repo description and the heading of the README still say Nano S.

**Comment by decentraliser** [comment]
Hi! Any news regarding this issue?

**Comment by Kryptoxic** [comment]
Been waiting for quite a while so I can test my app on the nano x. Any update on this?

**Comment by shufps** [comment]
afaik the nanox SDK is only available with NDA but they are planning to release it without NDA (somewhen).

But nobody knows how long it will take.

**Comment by TamtamHero** [comment]
A very recent addition, that you can use with Speculos https://github.com/LedgerHQ/nanox-secure-sdk
