### ISSUE TITLE
I gave up

### ISSUE THREAD

**Issue by vzhilov** [LedgerHQ/nanos-secure-sdk#26]
After installing all the dependacies, correct versions and pathes I still couln't get it working, so I gave up till furhter explanations are given. Here is what I get

> (ledger) server@DESKTOP:~/ledger-app-boilerplate$ make load
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=1.6.0
BOLOS_ENV is not set: falling back to CLANGPATH and GCCPATH
CLANGPATH is not set: clang will be used from PATH
GCCPATH is not set: arm-none-eabi-* will be used from PATH
BOLOS_ENV is not set: falling back to CLANGPATH and GCCPATH
CLANGPATH is not set: clang will be used from PATH
GCCPATH is not set: arm-none-eabi-* will be used from PATH
[CC]      obj/getAddress.o
src/getAddress.c:31:8: error: use of undeclared identifier 'C_icon_validate_14'
      &C_icon_validate_14,
       ^
/home/server/nanos-secure-sdk//lib_ux/include/ux_flow_engine.h:161:23: note: expanded from macro 'UX_STEP_VALID'
#define UX_STEP_VALID UX_STEP_CB
                      ^
src/getAddress.c:39:8: error: use of undeclared identifier 'C_icon_crossmark'
      &C_icon_crossmark,
       ^
/home/server/nanos-secure-sdk//lib_ux/include/ux_flow_engine.h:161:23: note: expanded from macro 'UX_STEP_VALID'
#define UX_STEP_VALID UX_STEP_CB
                      ^
2 errors generated.
/home/server/nanos-secure-sdk//Makefile.rules_generic:64: recipe for target 'obj/getAddress.o' failed
make: *** [obj/getAddress.o] Error 1

**Comment by kepoly** [comment]
Did you ever figure this issue out?

**Comment by kepoly** [comment]
Figured my issue out, using the boiler-plate code and running prepare-devenv.sh it checks out the SDK for 1.6.0, my device is running 1.6.1

**Comment by xchapron-ledger** [comment]
Closing this as this is old.
If you still have some trouble, please either use developer documentation on ledger website or use Discord link in the readme.
