### ISSUE TITLE
Deriving secrets for arbitrary crypto

### ISSUE THREAD

**Issue by immesys** [LedgerHQ/nanos-secure-sdk#6]
I am in the early stages of writing an app for the Ledger Nano S. I would like to derive a private key for use in an arbitrary cryptosystem (basically just deterministic entropy), what do I pass to `os_perso_derive_node_bip32` for the curve parameter? Also, is the result always 32 bytes?

Thanks

**Comment by TamtamHero** [comment]
You have a choice of multiple curves, the most common beeing `CX_CURVE_256K1`. 
You can find a complete list in cx.h
The output is 2 arrays of 32 bytes length: `privateKey` and `chain`.

**Comment by cslashm** [comment]
Hi, (quick answer.)

CX_CURVE_Curve25519 is not supported for know (It will be), but 
in openpgp app I need to generate deterministically keys  for RSA/ECDSA/EDDSA.


I did it  using master seed as described here: https://github.com/LedgerHQ/blue-app-openpgp-card/blob/master/doc/developper/gpgcard3.0-addon.rst#deterministic-key-derivation

Corresponding code is here:

- https://github.com/LedgerHQ/blue-app-openpgp-card/blob/master/src/gpg_gen.c#L134 RSA
- https://github.com/LedgerHQ/blue-app-openpgp-card/blob/master/src/gpg_gen.c#L172 ECC
- gpg_pso_derive_slot_seed and gpg_pso_derive_key_seed are at the beginning of the same file

I hope it will help.

**Comment by oto-ledger** [comment]
A new endpoint is coming to satisfy various derivation needs. Stay tuned for the 1.4.3.
